# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tendermint/statesync/types.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n tendermint/statesync/types.proto\x12\x14tendermint.statesync\"\x98\x02\n\x07Message\x12\x43\n\x11snapshots_request\x18\x01 \x01(\x0b\x32&.tendermint.statesync.SnapshotsRequestH\x00\x12\x45\n\x12snapshots_response\x18\x02 \x01(\x0b\x32\'.tendermint.statesync.SnapshotsResponseH\x00\x12;\n\rchunk_request\x18\x03 \x01(\x0b\x32\".tendermint.statesync.ChunkRequestH\x00\x12=\n\x0e\x63hunk_response\x18\x04 \x01(\x0b\x32#.tendermint.statesync.ChunkResponseH\x00\x42\x05\n\x03sum\"\x12\n\x10SnapshotsRequest\"c\n\x11SnapshotsResponse\x12\x0e\n\x06height\x18\x01 \x01(\x04\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\r\x12\x0e\n\x06\x63hunks\x18\x03 \x01(\r\x12\x0c\n\x04hash\x18\x04 \x01(\x0c\x12\x10\n\x08metadata\x18\x05 \x01(\x0c\"=\n\x0c\x43hunkRequest\x12\x0e\n\x06height\x18\x01 \x01(\x04\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\r\x12\r\n\x05index\x18\x03 \x01(\r\"^\n\rChunkResponse\x12\x0e\n\x06height\x18\x01 \x01(\x04\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\r\x12\r\n\x05index\x18\x03 \x01(\r\x12\r\n\x05\x63hunk\x18\x04 \x01(\x0c\x12\x0f\n\x07missing\x18\x05 \x01(\x08\x42=Z;github.com/tendermint/tendermint/proto/tendermint/statesyncb\x06proto3')



_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_SNAPSHOTSREQUEST = DESCRIPTOR.message_types_by_name['SnapshotsRequest']
_SNAPSHOTSRESPONSE = DESCRIPTOR.message_types_by_name['SnapshotsResponse']
_CHUNKREQUEST = DESCRIPTOR.message_types_by_name['ChunkRequest']
_CHUNKRESPONSE = DESCRIPTOR.message_types_by_name['ChunkResponse']
Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'tendermint.statesync.types_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.statesync.Message)
  })
_sym_db.RegisterMessage(Message)

SnapshotsRequest = _reflection.GeneratedProtocolMessageType('SnapshotsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOTSREQUEST,
  '__module__' : 'tendermint.statesync.types_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.statesync.SnapshotsRequest)
  })
_sym_db.RegisterMessage(SnapshotsRequest)

SnapshotsResponse = _reflection.GeneratedProtocolMessageType('SnapshotsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOTSRESPONSE,
  '__module__' : 'tendermint.statesync.types_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.statesync.SnapshotsResponse)
  })
_sym_db.RegisterMessage(SnapshotsResponse)

ChunkRequest = _reflection.GeneratedProtocolMessageType('ChunkRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHUNKREQUEST,
  '__module__' : 'tendermint.statesync.types_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.statesync.ChunkRequest)
  })
_sym_db.RegisterMessage(ChunkRequest)

ChunkResponse = _reflection.GeneratedProtocolMessageType('ChunkResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHUNKRESPONSE,
  '__module__' : 'tendermint.statesync.types_pb2'
  # @@protoc_insertion_point(class_scope:tendermint.statesync.ChunkResponse)
  })
_sym_db.RegisterMessage(ChunkResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z;github.com/tendermint/tendermint/proto/tendermint/statesync'
  _MESSAGE._serialized_start=59
  _MESSAGE._serialized_end=339
  _SNAPSHOTSREQUEST._serialized_start=341
  _SNAPSHOTSREQUEST._serialized_end=359
  _SNAPSHOTSRESPONSE._serialized_start=361
  _SNAPSHOTSRESPONSE._serialized_end=460
  _CHUNKREQUEST._serialized_start=462
  _CHUNKREQUEST._serialized_end=523
  _CHUNKRESPONSE._serialized_start=525
  _CHUNKRESPONSE._serialized_end=619
# @@protoc_insertion_point(module_scope)
